In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

df.drop(columns=["id","Unnamed: 32"], inplace=True)

In [4]:
df.shape

(569, 31)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [7]:
x_train.shape

(455, 30)

In [8]:
x_test.shape

(114, 30)

In [9]:
y_train.shape

(455,)

In [10]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
y_train

265    M
184    M
530    B
278    B
437    B
      ..
163    B
500    B
217    B
104    B
384    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,

In [14]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
x_train_tensor

tensor([[ 1.8729e+00,  2.8142e+00,  1.7976e+00,  ...,  7.6733e-01,
         -5.6042e-02, -1.3171e-01],
        [ 3.2586e-01,  7.4106e-01,  2.8357e-01,  ...,  1.0523e-01,
          4.3405e-01,  7.2089e-01],
        [-6.7615e-01, -4.1332e-01, -6.6443e-01,  ..., -2.2505e-01,
         -6.7863e-01, -3.8464e-01],
        ...,
        [-1.1161e+00, -4.3236e-01, -1.1106e+00,  ..., -1.2234e+00,
         -5.6042e-02, -3.5611e-01],
        [-1.0338e+00, -1.5536e-03, -1.0135e+00,  ..., -1.2797e+00,
         -1.2309e-01, -4.9711e-01],
        [-2.4185e-01, -1.3273e+00, -2.5691e-01,  ..., -3.6680e-01,
         -2.6677e-01, -6.2440e-01]], dtype=torch.float64)

In [20]:
class MySimpleNN():
  def __init__(self,X):
    # weight
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1- y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss


In [24]:
learning_rate = 0.1
epochs = 50

In [25]:
model = MySimpleNN(x_train_tensor)
# define loop
for epoch in range(epochs):
  # forward
  y_pred = model.forward(x_train_tensor)
  # loss
  loss = model.loss_function(y_pred, y_test_tensor)
  print(f"Epoch: {epoch+1}, loss: {loss.item()}")
  # backward
  loss.backward()
  # parameters update with no gradient
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch: {epoch+1}, loss: {loss.item()}")

Epoch: 1, loss: 4.059706448959728
Epoch: 1, loss: 4.059706448959728
Epoch: 2, loss: 3.948625207502819
Epoch: 2, loss: 3.948625207502819
Epoch: 3, loss: 3.8341990112545288
Epoch: 3, loss: 3.8341990112545288
Epoch: 4, loss: 3.7191082583491872
Epoch: 4, loss: 3.7191082583491872
Epoch: 5, loss: 3.6000324957379153
Epoch: 5, loss: 3.6000324957379153
Epoch: 6, loss: 3.4745924196176894
Epoch: 6, loss: 3.4745924196176894
Epoch: 7, loss: 3.342733059591035
Epoch: 7, loss: 3.342733059591035
Epoch: 8, loss: 3.207682367297936
Epoch: 8, loss: 3.207682367297936
Epoch: 9, loss: 3.0659505759464243
Epoch: 9, loss: 3.0659505759464243
Epoch: 10, loss: 2.919301880557691
Epoch: 10, loss: 2.919301880557691
Epoch: 11, loss: 2.76204134460034
Epoch: 11, loss: 2.76204134460034
Epoch: 12, loss: 2.6004356758031135
Epoch: 12, loss: 2.6004356758031135
Epoch: 13, loss: 2.4398405538146917
Epoch: 13, loss: 2.4398405538146917
Epoch: 14, loss: 2.282056623290237
Epoch: 14, loss: 2.282056623290237
Epoch: 15, loss: 2.1219727

In [26]:
model.weights

tensor([[-0.2838],
        [ 0.0215],
        [-0.1283],
        [ 0.1507],
        [-0.2827],
        [-0.0580],
        [-0.1703],
        [ 0.2173],
        [-0.2396],
        [-0.1235],
        [ 0.2176],
        [ 0.1257],
        [ 0.0623],
        [ 0.2877],
        [-0.2358],
        [ 0.3124],
        [-0.2901],
        [-0.0005],
        [ 0.1769],
        [ 0.1468],
        [ 0.3171],
        [ 0.1882],
        [-0.3411],
        [ 0.1160],
        [ 0.4430],
        [ 0.0392],
        [-0.5159],
        [-0.1454],
        [ 0.0283],
        [ 0.4202]], dtype=torch.float64, requires_grad=True)

In [27]:
model.bias

tensor([-0.2437], dtype=torch.float64, requires_grad=True)

In [33]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.6 ).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.6292705535888672
