In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU")

GPU is available
Using GPU: Tesla T4


##Creating a Tensor

In [ ]:
#Using empty
a = torch.empty(2,3)

In [ ]:
#Check types
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using random
torch.rand(2,3)*100

tensor([[13.6591, 95.8921, 33.4504],
        [ 7.8345, 16.2778,  1.2374]])

In [ ]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

# arange
print("using arange -->", torch.arange(1,10,2))

# using linespace
print("using linespace -->", torch.linspace(0,10,5))

# using eye
print("using eye -->", torch.eye(5))

# using full
print("using full -->", torch.full((3,3),5))


using arange --> tensor([1, 3, 5, 7, 9])
using linespace --> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye --> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


##Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
#create shame shape tensor but the value are different
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [ ]:
#create shame shape tensor but the value are 0
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
#create shame shape tensor but the value are 1
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
#create shame shape tensor but the value are random
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

##Tensor Data Type

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

##Mathematical Operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [ ]:
# item wise operations

# add
a+b
# sub
a-b
# multiply
a*b
#division
a/b
# mod
a%b
# power
a**b

tensor([[0.6515, 0.9868, 0.7919],
        [0.7388, 0.9763, 0.9243]])

In [ ]:
c = torch.tensor([1,-2,3])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3])

In [ ]:
# neg
torch.neg(c)

tensor([-1,  2, -3])

##Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float16)

In [ ]:
e

tensor([[5., 9., 9.],
        [7., 5., 9.]], dtype=torch.float16)

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([16, 12])

In [ ]:
# mean
torch.mean(e)
# mean along columns
torch.mean(e, dim=0)
# mean along rows
torch.mean(e, dim=1)

tensor([7.6680, 7.0000], dtype=torch.float16)

In [ ]:
# median
torch.median(e)

tensor(7., dtype=torch.float16)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(5., dtype=torch.float16)

In [ ]:
#product
torch.prod(e)

tensor(inf, dtype=torch.float16)

In [ ]:
# argmax
torch.argmax(e)

tensor(1)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)